services:
  app:
    build: .
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3002:3002"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SMTP_HOST=your-smtp-host
      - SMTP_PORT=587
      - SMTP_USER=your-smtp-user
      - SMTP_PASS=your-smtp-password
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - DATABASE_URL=postgresql://onprint:onprint789@postgres:5432/onprint?schema=public
    depends_on:
      redis:
        condition: service_healthy 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
       test: ["CMD", "redis-cli", "ping"]
       interval: 30s
       timeout: 5s
       retries: 3  
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:latest
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=onprint
      - POSTGRES_PASSWORD=onprint789
      - POSTGRES_DB=onprint
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "127.0.0.1:5050:80"  
    environment:
      - PGADMIN_DEFAULT_EMAIL=onprint@admin.com
      - PGADMIN_DEFAULT_PASSWORD=onprint789
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL="ERROR"
      - PGADMIN_CONFIG_FILE_LOG_LEVEL="ERROR"
      - PGADMIN_CONFIG_SESSION_EXPIRATION_TIME=86400
    depends_on:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis-data:
  postgres-data: